<!DOCTYPE html>
<html>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" />
	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/scripts.js"></script>
	<head></head>



	<body>
		<div id="wrap">
			<div id="user_block">
				<? if($this->authUser->canAddPost()):?>
					<?=$this->authUser->name;?>
					<a href="/index/logout">exit</a>
				<? else: ?>
					<form id="auth_form"> 
						Login: <input type="text" name="login">
						<br>Pass: <input type="password" name="pass">
						<br><input type="button" id="auth_button" value="Send">
					</form>
				<? endif;?>
			</div>
			<div id="content">
				<?=$this->content;?>
			</div>

			<? if($this->authUser->canAddPost()):?>
				<div id="add_post_block"><a href="/post/addpostform">Добавить пост</a></div>
			<? endif;?>
		</div>
	</body>
</html>